name: Create data bundle

on:
  schedule:
    - cron: '15 20 * * *'

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test-branch
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create bundle file
        run: python bundle.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit updated data bundle
        with:
          commit_message: automatic - Data bundle updated
